---
- name: Copy custom_facts.fact to servers
  hosts: all

  tasks:
    - name: Ensure /etc/ansible/facts.d directory exists
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        mode: '0755'

    - name: Copy custom_facts.fact to /etc/ansible/facts.d
      ansible.builtin.copy:
        src: host_vars/{{ inventory_hostname }}.fact
        dest: /etc/ansible/facts.d/custom_facts.fact
        mode: '0644'
