---
- name: Execute group-specific tasks
  hosts: all
  become: yes

  tasks:
    - name: Include tasks for webservers group
      include_tasks: tasks/webservers.yml
      when: "'webservers' in group_names"

    - name: Include tasks for databases group
      include_tasks: tasks/databases.yml
      when: "'databases' in group_names"

    - name: Include tasks for developer_servers group
      include_tasks: tasks/developer_servers.yml
      when: "'developer_servers' in group_names"

    - name: Perform Security hardening on Secure VLAN (10.8.50.X)
      include_tasks: tasks/hardening.yml
      when: ansible_facts.default_ipv4.network is defined and ansible_facts.default_ipv4.network.startswith("10.8.50")
