---
- name: Task specific to database_servers
  ansible.builtin.debug:
    msg: "Executing tasks for database_servers group" 

- name: Create a new database with name "acme"
  community.postgresql.postgresql_db:
    name: acme
    comment: My test DB
