---
- name: Task specific to database_servers
  ansible.builtin.debug:
    msg: "Executing tasks for database_servers group" 

- name: Configure postgresql using role
  import_role:
    name: linux-system-roles.postgresql
  become: yes
  become_user: root
